function [cost, grad] = mlpCost(theta, ...
                                visibleSize, ...
                                hiddenSizeL1, hiddenViewSizeL1, ...
                                hiddenSizeL2, hiddenViewSizeL2, ...
                                W1Indices, W2Indices, ...
                                lambda, data, labels)
  cost = 0;
  grad = zeros(size(theta));
end
